import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'

import StoreProvider from '@/lib/store/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={"flex w-full items-start justify-center bg-green-200"}>
          <div className="p-5">
            <Image
              src="/logo.webp"
              alt="Logo"
              // className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
              width={400}
              height={50}
              priority
            />
          </div>
        </div>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html >
  )
}
